class EmailAlreadyRegistered(ValueError): ...


class UsernameTaken(ValueError): ...


class InvalidCredentials(ValueError): ...


class EmailNotVerified(Exception): ...


class InvalidVerificationToken(Exception): ...
